name: Comprehensive CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes to continually optimize the code

jobs:
  build-and-optimize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Python 3.10 is currently the latest supported major release

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install openai flake8 pytest  # Ensure all necessary packages for running tests and linting are installed

      - name: Lint with Flake8
        run: flake8 .
        continue-on-error: true  # This allows the workflow to continue even if linting fails

      - name: Run Tests with Pytest
        run: pytest
        continue-on-error: true  # This allows the workflow to continue even if some tests fail

      - name: Optimize Code with OpenAI Codex
        run: python optimize_code.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        continue-on-error: true  # This allows the workflow to continue even if optimization fails

      - name: Commit and Push Changes if There Are Any
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Automate optimization and improvement of Python code with OpenAI Codex"
          git push
        continue-on-error: true  # This allows the workflow to continue even if there's nothing to commit

      - name: Notify Slack on Failure
        if: failure()  # Only runs if any of the previous steps failed
        uses: rtCamp/action-slack-notify@v2
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: '#deploy-alerts'
          username: 'GitHub Actions'
          icon_emoji: ':scream:'
          title: 'Failure in Workflow'
          message: 'One or more steps in the workflow failed. Check the GitHub Actions logs for more details.'
          color: '#FF0000'

