name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, '3.x']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest --cov=./

    - name: Build and Push Docker image (Optional)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        echo "Pushing Docker Image..."
        # commands to build and push Docker image

    - name: Notify Slack (Optional)
      if: failure() && github.ref == 'refs/heads/main'
      uses: slackapi/slack-github-action@v1.18.0
      with:
        slack-message: "Build Failed :x: - ${{ github.run_id }}"
