name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: flake8 .
      continue-on-error: true

    - name: Test with pytest
      run: pytest
      continue-on-error: true

    - name: Optimize Code with OpenAI Codex
      run: python optimize_code.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      continue-on-error: true

    - name: Commit and Push Changes if Exist
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git diff --quiet && git diff --staged --quiet || (git commit -am "Automate optimization of Python code with OpenAI Codex" && git push)
        continue-on-error: true

    - name: Notify Slack on Failure
      if: failure()  # This will trigger if any of the previous steps fail
      uses: rtCamp/action-slack-notify@v2
      with:
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        channel: '#your-channel'  # Ensure the channel is specified correctly
        username: 'GitHub Actions'
        icon_emoji: ':scream:'
        title: 'Failure in CI/CD Workflow'
        message: 'One or more steps in the workflow failed. Check the GitHub Actions logs for details.'
        color: '#FF0000'
