name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Test with pytest
      run: |
        pip install pytest
        pytest

    - name: Notify Slack on Failure
      if: failure()  # This step will run only if any of the previous steps fail
      uses: slackapi/slack-github-action@v1.18.0
      with:
        slack-message: "Build Failed :x: - ${{ github.run_id }}"
        webhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
