name: Advanced CI/CD Pipeline for Voice Cloning GUI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Flake8
        run: flake8 .

      - name: Run Tests
        run: pytest

      - name: Build and Push Docker Image
        if: github.ref == 'refs/heads/main' && matrix.python-version == '3.10'
        run: |
          echo "Building and pushing Docker image..."
          docker build -t voice-cloning-gui .
          docker push username/voice-cloning-gui:latest

      - name: Notify Slack on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: '#deployments'
          username: 'GitHub Actions'
          icon_emoji: ':boom:'
          title: 'Build or Test Failed'
          message: '${{ github.workflow }} failed!'
          color: '#FF0000'
