name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install flake8 pytest

    - name: Run flake8
      run: flake8 .

    - name: Run pytest
      run: pytest

    - name: Run optimize_code.py
      run: python optimize_code.py
      env:
        API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Configure git
      run: git config --global user.name 'GitHub Actions Bot'

    - name: Notify on Slack
      uses: rtCamp/action-slack-notify@v2
      with:
        slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

    - name: Post job cleanup
      run: |
        git config --global --add safe.directory /home/runner/work/CHANGER/CHANGER
        git config --local --name-only --get-regexp core\.sshCommand
        git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
