name: Continuous Code Optimization

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes

jobs:
  optimize-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install OpenAI Library
        run: pip install openai

      - name: Optimize Python Code
        run: python optimize_repository.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit and Push Changes if Exist
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git diff --quiet && git diff --staged --quiet || (git commit -am "Automated optimization of Python code with OpenAI Codex" && git push)
