name: Enhanced Comprehensive CI/CD Automation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Ensures initialization of known submodules

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Setup Environment Paths
        run: |
          echo "/opt/hostedtoolcache/Python/3.8.18/x64/bin" >> $GITHUB_PATH
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Install and List Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 pytest sphinx
          pip list  # Outputs the list of installed packages for verification

      - name: Auto-formatting with Black and Linting with Flake8
        run: |
          black --check --diff --quiet .
          flake8 . --extend-ignore=E501,F405

      - name: Execute Tests
        run: |
          pytest -vv

      - name: Generate Docs with Sphinx
        run: |
          sphinx-build -b html ./docs/source ./docs/build

      - name: Cleanup and Finalize
        run: |
          find . -name "*.tmp" -delete  # Example cleanup operation

      - name: Notify on Slack with Workflow Status
        if: always()  # Ensures notification triggers on both success and failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          status: ${{ job.status }}
          fields: 'job,ref,commit,repo,author'
