name: Enhanced Comprehensive CI/CD Automation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3
        
      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 pytest sphinx
          pip list

      - name: Setup Environment Paths
        run: |
          echo "/opt/hostedtoolcache/Python/3.8.18/x64/bin" >> $GITHUB_PATH
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Auto-formatting with Black and Linting with Flake8
        run: |
          black --check --diff --quiet .
          flake8 . --extend-ignore=E501,F405

      - name: Execute Tests
        run: |
          pytest -vv

      - name: Generate Documentation with Sphinx
        run: |
          sphinx-build -b html ./docs/source ./docs/build

      - name: Cleanup Temporary Files
        run: |
          find . -name "*.tmp" -delete

      - name: Notify on Slack with Workflow Status
        if: always()  # This ensures that the notification step will run regardless of previous steps' success or failure.
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          status: ${{ job.status }}
          fields: 'job,ref,commit,repo,author'
