name: Comprehensive CI/CD Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore: 
      - '**/*.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Formatting Python Code with Black
      run: black --check --diff --quiet .

    - name: Lint with flake8
      run: flake8 . --extend-ignore=E501
    
    - name: Run Automated Tests
      run: |
        pytest

    - name: Auto-Fix and Validation Checks
      run: python .github/scripts/fix_and_validate.py

    - name: Notify on Slack
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      with:
        status: ${{ job.status }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
